GET http://localhost:8080/products
###
GET http://localhost:8080/products/1
###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "PC",
  "price": 1000.0
}
###
POST http://localhost:8080/products
Content-Type: application/json

{
  "price": 1200.0
}
###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "L",
  "price": 1200.0
}
###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "L2"
}
###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "L2",
  "price": -1200.0

}
